export const TopLink = [
  {
    title: "Jade Terrarium",
    price: "Rp 200.000.000",
    img: "/images/jade.png",
    desc: "bahan berkualitas",
    rating: "4.9",
    sold: "1",
  },
  {
    title: "Ficus Benjamina",
    price: "Rp 1.500.000",
    img: "/images/ficus.png",
    desc: "bahan berkualitas",
    rating: "4.2",
    sold: "4",
  },
  {
    title: "Syngorium Plant",
    price: "Rp 8.000.000",
    img: "/images/syngorium.png",
    desc: "bahan berkualitas",
    rating: "4.5",
    sold: "1",
  },
  {
    title: "Cactus Peruvianus",
    price: "Rp 17.000.000",
    img: "/images/cactuss.png",
    desc: "bahan berkualitas",
    rating: "4.4",
    sold: "2",
  },
  {
    title: "Cactus Peruvianus",
    price: "Rp 17.000.000",
    img: "/images/cactuss.png",
    desc: "bahan berkualitas",
    rating: "4.4",
    sold: "2",
  },
  {
    title: "Cactus Peruvianus",
    price: "Rp 17.000.000",
    img: "/images/cactuss.png",
    desc: "bahan berkualitas",
    rating: "4.4",
    sold: "2",
  },
  {
    title: "Cactus Peruvianus",
    price: "Rp 17.000.000",
    img: "/images/cactuss.png",
    desc: "bahan berkualitas",
    rating: "4.4",
    sold: "2",
  },
  {
    title: "Cactus Peruvianus",
    price: "Rp 17.000.000",
    img: "/images/cactuss.png",
    desc: "bahan berkualitas",
    rating: "4.4",
    sold: "2",
  },
];
